name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Docker
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
    - name: Build Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME}}/quizscape-cms-frontend:latest .
    - name: Push Image To DockerHub :)
      run: docker push ${{ secrets.DOCKER_USERNAME }}/quizscape-cms-frontend:latest
